### ISSUE TITLE
Allow optional RawRepresentable Field

### ISSUE THREAD

**Issue by saugsburger-amaris** [amaris/core-data-candy#32]
For now, if we declare a `Field` that is mapped to a `RawRepresentable`, optional values are supported for reading (eg. initial value can be `nil`) but it isn't supported for writing.

This has to be handled in `FieldInterfaceProtocol.swift#74`

**Comment by ABridoux** [comment]
This is a general behavior, if a value is `nil` when trying to store it in CoreData, it will not be stored. Thus, the solution might be to find to way to allow `nil` value to be set on optional attributes in the `FieldInterfaceProtocol.set`  implementation of `FieldModifier`.
